version: "3"
services:
    redis:
        image: redis
        restart: always
        container_name: redis
        entrypoint: ["redis-server"]
        volumes: 
            - dbdata:/data/db
        ports:
            - '6379:6379'
        networks: 
            - chatnetwork
    server:
        image: chatterserver.azurecr.io/chatservice:latest
        restart: always
        ports:
            - "8080:8080"
        entrypoint: ["npm", "start"]
        environment: 
            - PORT=8080
            - REDIS_HOST=redis
        links: 
            - redis
        networks: 
            - chatnetwork
networks: 
    chatnetwork:
        driver: bridge
volumes:
    dbdata: